export declare const container: string;
export declare const dropButton: string;
export declare const dropContainer: string;
export declare const getButtonItemCy: (index: string, name?: string) => string;
export declare const getButtonItemConfirmCy: (index: string, name?: string) => string;
export declare const getButtonItemIndexCy: (index: string) => string;
export declare const getButtonItemConfirmIndexCy: (index: string) => string;
export declare const getMenuItemCy: (index: string, name?: string) => string;
export declare const getMenuItemConfirmCy: (index: string, name?: string) => string;
export declare const getMenuItemIndexCy: (index: string) => string;
export declare const getMenuItemConfirmIndexCy: (index: string) => string;
export declare const btnItemId: string;
export declare const dropBtnId: string;
export declare const menuContainerId: string;
export declare const menuItemId: string;
export declare const groupDividerId: string;
