import type { ReactElement } from 'react';
import React from 'react';
import type { TransferCheckStrategy, TreeTransferDataType } from '../interface';
import { LoadType } from '../interface';
import type { NodeProps, TreeProps } from '@arco-design/web-react/es/Tree/interface';
import type { TreeTransferHelper } from '../class';
interface RenderTreeProps {
    treeData: TreeTransferDataType[];
    hasLoadMore: boolean;
    checkedKeys?: string[];
    halfCheckedKeys?: string[];
    treeProps?: TreeProps;
    type: 'source' | 'target';
    firstLevelHasMore?: boolean | 'error';
    helper: TreeTransferHelper;
    targetExpandKeys?: string[];
    emptyContent?: ReactElement;
    checkedStrategy?: TransferCheckStrategy;
    itemRender?: (item: NodeProps, treeData?: TreeTransferDataType[]) => React.ReactNode;
    onLoadMore?: (keyPath: string[]) => void;
    onRemove?: (item: NodeProps) => void;
    onCheck?: (node: NodeProps, checked: boolean, checkedKeys: string[]) => void;
    onTargetExpandChange?: (keys: string[]) => void;
    dataCy: string;
    loadType?: LoadType;
    isEmptyShowLoadMore: boolean;
    isAutoExpandSource?: boolean;
    isAutoExpandTarget?: boolean;
}
export declare const RenderTree: React.FC<RenderTreeProps>;
export {};
