/// <reference types="react" />
export declare const ModalFormStep: (<FormData_1 extends import("../CForm").ObjectType = import("../CForm").ObjectType, GlobalData extends import("../CForm").ObjectType = import("../CForm").ObjectType>(props: import("../_factory/maskableComponent").BuiltInFormProps<import("./interface").CModalProps & import("react").RefAttributes<HTMLDivElement>, "stepConfig", Omit<Omit<{}, never>, keyof import("../CForm").DefaultBuiltInComponentMapType> & import("../CForm").DefaultBuiltInComponentMapType, FormData_1, GlobalData, any, any>) => import("react").ReactElement<any, string | import("react").JSXElementConstructor<any>> | null) & {
    create: import("../_factory/maskableComponent").CreateBuiltIn<import("./interface").CModalProps & import("react").RefAttributes<HTMLDivElement>, "stepConfig">;
} & Omit<import("react").JSXElementConstructor<import("../_factory/maskableComponent").BuiltInFormProps<import("./interface").CModalProps & import("react").RefAttributes<HTMLDivElement>, "stepConfig", Omit<Omit<{}, never>, keyof import("../CForm").DefaultBuiltInComponentMapType> & import("../CForm").DefaultBuiltInComponentMapType, import("../CForm").ObjectType, import("../CForm").ObjectType, any, any>> & {
    open: <P extends unknown = any>(props: import("../_factory/maskableComponent").StaticMethodsExtraProps<Omit<import("./interface").CModalProps & import("react").RefAttributes<HTMLDivElement>, "onOk" | "onCancel"> & {
        footerFields?: import("../CForm").CFormFooterItem<import("../CForm").ObjectType, import("../CForm").ObjectType>[] | undefined;
        decoratorProps?: import("../_factory/maskableComponent").MaskableFormDecoratorProps | undefined;
        formFooter?: ((renderCancelBtn: import("../CForm").CFormFooterCustomRender, prevStepBtn: import("../CForm").CFormFooterBuiltInButton, nextStepBtn: import("../CForm").CFormFooterBuiltInButton, okBtn: import("../CForm").CFormFooterBuiltInButton, formStep: import("../CForm").CFormStep) => import("../CForm").CFormFooterItem<import("../CForm").ObjectType, import("../CForm").ObjectType>[]) | undefined;
        formProps?: import("../CForm").CFormProps<import("../CForm").ObjectType, import("../CForm").ObjectType, Omit<Omit<{}, never>, keyof import("../CForm").DefaultBuiltInComponentMapType> & import("../CForm").DefaultBuiltInComponentMapType, import("react").JSXElementConstructor<import("@storage-fe/formily-arco/es/FormStep/types").FormStepDecoratorProps>> | undefined;
        formConfig: import("../CForm").CFormStepConfig<import("../CForm").ObjectType, import("../CForm").ObjectType, Omit<Omit<{}, never>, keyof import("../CForm").DefaultBuiltInComponentMapType> & import("../CForm").DefaultBuiltInComponentMapType>;
        formRef?: import("react").Ref<import("../CForm").CForm<import("../CForm").ObjectType, import("../CForm").ObjectType> | null> | undefined;
        onOk?: ((values: import("../CForm").ObjectType, form: import("../CForm").CForm<import("../CForm").ObjectType, import("../CForm").ObjectType>) => any) | undefined;
        onCancel?: ((e?: MouseEvent | undefined) => any) | undefined;
    }>) => import("../_factory/maskableComponent").StaticMethodsReturn<Omit<import("./interface").CModalProps & import("react").RefAttributes<HTMLDivElement>, "onOk" | "onCancel"> & {
        footerFields?: import("../CForm").CFormFooterItem<import("../CForm").ObjectType, import("../CForm").ObjectType>[] | undefined;
        decoratorProps?: import("../_factory/maskableComponent").MaskableFormDecoratorProps | undefined;
        formFooter?: ((renderCancelBtn: import("../CForm").CFormFooterCustomRender, prevStepBtn: import("../CForm").CFormFooterBuiltInButton, nextStepBtn: import("../CForm").CFormFooterBuiltInButton, okBtn: import("../CForm").CFormFooterBuiltInButton, formStep: import("../CForm").CFormStep) => import("../CForm").CFormFooterItem<import("../CForm").ObjectType, import("../CForm").ObjectType>[]) | undefined;
        formProps?: import("../CForm").CFormProps<import("../CForm").ObjectType, import("../CForm").ObjectType, Omit<Omit<{}, never>, keyof import("../CForm").DefaultBuiltInComponentMapType> & import("../CForm").DefaultBuiltInComponentMapType, import("react").JSXElementConstructor<import("@storage-fe/formily-arco/es/FormStep/types").FormStepDecoratorProps>> | undefined;
        formConfig: import("../CForm").CFormStepConfig<import("../CForm").ObjectType, import("../CForm").ObjectType, Omit<Omit<{}, never>, keyof import("../CForm").DefaultBuiltInComponentMapType> & import("../CForm").DefaultBuiltInComponentMapType>;
        formRef?: import("react").Ref<import("../CForm").CForm<import("../CForm").ObjectType, import("../CForm").ObjectType> | null> | undefined;
        onOk?: ((values: import("../CForm").ObjectType, form: import("../CForm").CForm<import("../CForm").ObjectType, import("../CForm").ObjectType>) => any) | undefined;
        onCancel?: ((e?: MouseEvent | undefined) => any) | undefined;
    }, P>;
    close: (id?: number | undefined) => void;
}, "open"> & {
    open: <FormData_2 extends import("../CForm").ObjectType = import("../CForm").ObjectType, GlobalData_1 extends import("../CForm").ObjectType = import("../CForm").ObjectType, OnOkReturn = any, OnCancelReturn = any>(props: import("../_factory/maskableComponent").StaticMethodsExtraProps<import("../_factory/maskableComponent").BuiltInFormProps<import("./interface").CModalProps & import("react").RefAttributes<HTMLDivElement>, "stepConfig", Omit<Omit<{}, never>, keyof import("../CForm").DefaultBuiltInComponentMapType> & import("../CForm").DefaultBuiltInComponentMapType, FormData_2, GlobalData_1, OnOkReturn, OnCancelReturn>>) => import("../_factory/maskableComponent").StaticMethodsReturn<import("../_factory/maskableComponent").BuiltInFormProps<import("./interface").CModalProps & import("react").RefAttributes<HTMLDivElement>, "stepConfig", Omit<Omit<{}, never>, keyof import("../CForm").DefaultBuiltInComponentMapType> & import("../CForm").DefaultBuiltInComponentMapType, FormData_2, GlobalData_1, OnOkReturn, OnCancelReturn>, OnOkReturn | OnCancelReturn>;
};
